packages/react-material-ui/package.json

This PR updates the package.json to not force any types version. When we define a resolution we're telling that we'd want to use that specific version. The problem with this approach is that the project that implements rockets-react might have a completely different version of the types and we'd be installing two different versions of the types, giving type conflicts and typescript errors.
We're heavily touching on material ui, and this part of rockets-react is event called react-material-ui so it's a good practice to follow their standard, check this reference: 
https://github.com/mui/material-ui/blob/master/packages/mui-lab/package.json

fix: tweak dependency tree to use correct react types

---

packages/react-material-ui/src/components/Table/Table.tsx
packages/react-material-ui/src/components/Table/TableHeaders.tsx
packages/react-material-ui/src/components/Table/useTable.ts

This PR aims to add the following tweaks to the Table component in order to make it more flexible.
- Add empty state display
- Table Custom Row
- Make sortableValue optional
- Allow sortableValue to be a number or string
- Prop to remove pagination and show full list
- Add title (popup info) to cell
- Header styles
We're also updating the following in the usetable hook:
- Add DataProviderRequest (onError, onSuccess, onFinish) props
- Add ability to fetch data without pagination
```
<Table
emptyMessage="No users found!" // Defaults to "No records found" based on total && rows.length
...
/>
```
```
<Table
noPagination
...
/>
const { data, tableProps } = useTable('user', {
noPagination: true
});
```
```
const headers: HeadersProps[] = [
...
{
id: 'name',
label: 'Name',
sortable: false, // …
```

feat: add table small tweaks

---

packages/react-material-ui/src/components/ContainerWithDrawer/ContainerWithDrawer.tsx

This PR extends ContainerWithDrawer to receive any given styles. The initial idea was to replace height with minHeight but this can limit some projects layouts. So let's have height as default and make it extendable.
```
<ContainerWithDrawer
...
sx={{
height: 'auto',
minHeight: '100vh'   
}}
...
/>
```

feat: add sx prop to ContainerWithDrawer

---

packages/react-auth-provider/src/index.tsx
packages/react-data-provider/src/ClientProvider.tsx
packages/react-data-provider/src/axiosClient.ts
packages/react-data-provider/src/interfaces/index.ts
packages/react-data-provider/src/useDataProvider.ts
packages/react-material-ui/src/components/Table/useTable.ts

This PR adds the ability to refresh the access token using refreshToken and it fails it executes a callback passed to ClientProvider at the same time that it removes both accessToken and refreshToken from localStorage.
It also adds the refreshToken to the localStorage.

feat: add unauthorized handler to DataProvider and expose refreshToken

---

packages/react-material-ui/src/components/Table/TableBody/TableBodyRows.tsx
packages/react-material-ui/src/components/Table/TableCellSkeleton.tsx
packages/react-material-ui/src/components/Table/TableRowSkeleton.tsx
packages/react-material-ui/src/components/Table/index.ts
packages/react-material-ui/src/components/Table/useTable.ts

This PR adds table skeleton loading as default for Table.BodyRows loading state.
It also fixes a minor issue on simpleFilter update.
```
<Table.BodyRows isLoading={isLoading} />
```

feat: add table skeleton loading

---

packages/react-material-ui/src/components/SearchField/index.tsx
packages/react-material-ui/src/components/Table/useTable.ts
packages/react-material-ui/src/index.ts

This PR adds SearchField component.
```
<SearchField
defaultValue={defaultValue}
onDebouncedSearchChange={search =>
makeRequestToApi(search)
}
/>
```
```
<SearchField
onDebouncedSearchChange={search =>
makeRequestToApi(search)
}
searchIconPlacement="start" // by default it is set to "end"
/>
```
```
<SearchField
size="small"
placeholder="Search by anything you want"
onDebouncedSearchChange={search =>
makeRequestToApi(search)
}
/>
```

feat: add search field component

---

packages/react-material-ui/src/components/FormFieldSkeleton/index.tsx
packages/react-material-ui/src/components/TextField/TextField.tsx
packages/react-material-ui/src/index.ts
packages/react-material-ui/src/styles/CustomWidgets/CustomAutocompleteWidget.tsx
packages/react-material-ui/src/styles/CustomWidgets/index.ts

This PR aims to add Autocomplete widget to be using within RSJF.
```
export const uiSchema: UiSchema = {
country: {
'ui:widget': CustomAutocompleteWidget,
// this is optional, if not provided the request will not be made
// and the values to the autocomplete must be provided in an enum fashion
'ui:resource': '/countries',
// this is optional, defaults to 'id' and 'name' respectively
'ui:resourceLabel': 'label'
'ui:resourceValue': 'mainId'
},
};
```

feat: add autocomplete widget

---

packages/react-material-ui/src/components/SearchField/SearchField.tsx
packages/react-material-ui/src/components/Table/hooks/useTableQueryState.ts
packages/react-material-ui/src/components/Table/types.ts
packages/react-material-ui/src/components/Table/useTable.ts

This PR exports `updateSearch` and fixes search params when dealing with search param.
It also adds a fix for SearchField to not trigger handleDebouncedSearch on first render.
PS: This will be refactored when we add the query builder based on `nestjsx/crud-request` module.

feat: add update search

---

packages/react-material-ui/src/components/AutocompleteField/AutocompleteField.tsx
packages/react-material-ui/src/components/FormFieldSkeleton/index.tsx
packages/react-material-ui/src/components/SelectField/SelectField.tsx
packages/react-material-ui/src/styles/CustomWidgets/CustomAutocompleteWidget.tsx

Solves #55 
This PR removes the fixed width from `FormFieldSkeleton`, wrapping the component around the field so it can get the correct width when width is customized.

feat: form field skeleton size and rendering improvements

---

packages/react-material-ui/src/components/Drawer/Styles.tsx
packages/react-material-ui/src/components/Table/TableBody/TableBodyRows.tsx
packages/react-material-ui/src/components/Table/TableHeader/TableHeaderCells.tsx
packages/react-material-ui/src/components/Table/types.ts

Refactor lines that cause warning on projects that import specific components. Some of those warnings were caused by custom props bring forwarded to DOM elements, which led to the DOM not recognizing them as valid properties.
Further reference: [Mui Custom Components](https://mui.com/system/styled/#custom-components)

Fix lines that cause warning on other projects

---

packages/react-material-ui/src/components/Table/useTable.ts

Solves #55 
This PR makes it possible to use a search directly passing the boolean value without need to use `$eq` operator.

fix: do not coerce falsy values inside usetable filters

---

packages/react-data-provider/src/useDataProvider.ts

This PR fixes the refresh token response not being exposed in the local storage.

fix: add refresh token response to local storage

---

packages/react-material-ui/src/components/Table/TableRoot.tsx
packages/react-material-ui/src/components/Table/useTable.ts

This PR adds a check to know if it's the first render to prevent from resetting the page in the table state. Currently, when we update a search or a simple filter, we reset the page so we can have the filter from the page one. When updateSearch/updateSimpleFilter is used within a useEffect it will reset the page in the first render. These changes prevent this behavior.

fix: remove page reset when it's first render

---

packages/react-material-ui/package.json
packages/react-material-ui/src/components/submodules/AuthForm/index.tsx
packages/react-material-ui/src/components/submodules/DrawerForm/index.tsx
packages/react-material-ui/src/components/submodules/ModalForm/index.tsx
packages/react-material-ui/src/components/submodules/Table/index.tsx
packages/react-material-ui/src/modules/auth/README.md
packages/react-material-ui/src/modules/auth/index.tsx
packages/react-material-ui/src/modules/crud/README.md
packages/react-material-ui/src/modules/crud/index.tsx
yarn.lock

Implementaion of handler props for success/error on modules. The reason for that is beacuse having an opinionated `toast` implementation for those types of functions doesn't work on other projects.

Implement feedback handlers as module props

---

packages/react-material-ui/src/components/Filter/Filter.tsx
packages/react-material-ui/src/components/OrderableDropDown/OrderableDropDown.tsx

This PR adds an unique identifier to the key of the filter. We can't use the `index` of the item in the array as unique identifier because since we're changing the orders of the items. Let's say that we have two filter: 1) name, 2) email. If we use the `index` for the key prop and then change move email to the first element of the array then `React` will infer wrong props in both fields.
This is also the reason why `Autocomplete` was not "persisting" the state visually.

fix: change filter id and standardize component pattern

---

packages/react-material-ui/src/components/submodules/Table/index.tsx
packages/react-material-ui/src/modules/crud/index.tsx
packages/react-material-ui/src/modules/users/constants.ts

This PR adds the ability to pass a function `renderTableCell` for a given header. This function has the following signature:
```
renderTableCell?: (data: unknown) => CustomTableCell;
```
```
...
{
id: "fullName",
label: "Full name",
renderTableCell: data => ({
component: (
<div
style={{
background: "red",
}}
>
{data}
</div>
),
}),
},
...
```

feat: add renderTableCell to crud modules

---

packages/react-material-ui/src/components/submodules/Table/index.tsx
packages/react-material-ui/src/modules/crud/index.tsx

[Crud Module Format Improvements](https://sprints.zoho.com/workspace/conceptatech#P112/itemdetails/I1328)
This MR does this and that...
- Fixes the tableRows map function, to allow to use format for id's that don't exist in the row data
- Allow the tableRows format to return a ReactNode

feat: fix format function bug, allow format to return react node

---

packages/react-material-ui/src/components/SchemaForm/utils/mapAdvancedProperties.ts
packages/react-material-ui/src/components/SchemaForm/utils/mapEnumToCheckbox.ts
packages/react-material-ui/src/components/SchemaForm/utils/mapEnumToSchema.ts
packages/react-material-ui/src/components/SchemaForm/utils/mapWidgetType.ts
packages/react-material-ui/src/components/SchemaForm/utils/mergeFormData.ts
packages/react-material-ui/src/components/SchemaForm/utils/uiSchemaGenerator.ts
packages/react-material-ui/src/components/TextField/PasswordStrength.tsx
packages/react-material-ui/src/components/TextField/PasswordStrengthBar.tsx
packages/react-material-ui/src/components/TextField/PasswordStrengthRules.tsx
packages/react-material-ui/src/components/TextField/TextField.tsx
packages/react-material-ui/src/components/TextField/constants.ts
packages/react-material-ui/src/components/TextField/utils.ts
packages/react-material-ui/src/styles/CustomWidgets/CustomPasswordFieldWidget.tsx

This PR implements the password strength components inside the TextField. The password strength features can be used both directly on TextField or through CustomPasswordFieldWidget.
We use defaults for the password rules, score validation and texts, but everything piece can be customized either passing a render function or passing different rule values.
By default, the password strength is hidden in the TextField component. If we want to use it, we must explicitly tell the component to render it. Here are the new props that TextField accepts.
```
export type PasswordStrengthConfig = {
hideRulesText?: boolean;
hideStrengthBar?: boolean;
rules?: PasswordRule[];
matchRules?: {
text: string[];
score: number[];
};
renderStrengthBar?: (
variant: PasswordStrengthBarVariants,
text: string,
) => …
```

feat: add password strength component

---

packages/react-material-ui/src/components/Filter/Filter.tsx
packages/react-material-ui/src/components/OrderableDropDown/OrderableDropDown.tsx
packages/react-material-ui/src/components/Table/TableColumnOrderable.tsx
packages/react-material-ui/src/components/submodules/Table/index.tsx
packages/react-material-ui/src/modules/crud/index.tsx

Modifications of the Filter submodule placement and grid structure. The idea was to have the top row displaying all inputs/actions related to the filters and the bottom row being related to the table itself and/or actions that modify it.

Change layout of filters and actions on Filter submodule

---

packages/react-material-ui/src/components/Filter/Filter.tsx
packages/react-material-ui/src/components/OrderableDropDown/OrderableDropDown.tsx

The issue is that when a Date filter input is hidden, its value is not removed from the current filter object, which results in the table data not changing and always filtering from a field that does not exist.

Adjust auto clean when filter is hidden for Date fields

---

packages/react-material-ui/src/components/submodules/DrawerForm/index.tsx
packages/react-material-ui/src/components/submodules/ModalForm/index.tsx

When passing the `title` prop inside the Crud module schema form, the string was being duplicated on top of the form. This PR fixes this issue by displaying the form title string as the modal title.
If no title is passed in the schema, the module title is displayed on top of the form.

Change how the crud form title prop is displayed

---

packages/react-auth-provider/src/index.tsx
packages/react-material-ui/__tests__/Filter.spec.tsx
packages/react-material-ui/src/components/Filter/Filter.tsx
packages/react-material-ui/src/components/OrderableDropDown/OrderableDropDown.tsx
packages/react-material-ui/src/components/Table/Table.tsx
packages/react-material-ui/src/components/Table/TableOptions.tsx
packages/react-material-ui/src/hooks/useSettingsStorage.ts
packages/react-material-ui/src/utils/settings/storage.ts

The scope of this PR is to implement persistence for the Filter data on localStorage (for now, the idea is to have this integrated with BE in the future) every time the user changes the settings (toggle and/or change order of filters). To structure the data saved, the `react-auth-provider` and `next/navigation` libs are used, for getting the logged user data and the current route, respectively.
The structure consists of an array of objects, each one representing settings related to a specific user, as follows:
```json
[
{
"userId":"USER_ID",
"settingsId":"SETTINGS_ID",
"list":"SETTINGS_LIST"
}
]
```
The array is saved on storage with the `filterSettings` key.
`userId`: unique id of the user logged in;
`settingsId`: prop representing an identifier for the settings object. if no value is …

Save Filter settings on local storage

---

packages/react-material-ui/__tests__/ComposedTable.spec.tsx
packages/react-material-ui/__tests__/Filter.spec.tsx
packages/react-material-ui/src/components/ComposedTable/constants.ts
packages/react-material-ui/src/components/ComposedTable/index.tsx
packages/react-material-ui/src/components/Filter/Filter.tsx
packages/react-material-ui/src/hooks/useSettingsStorage.ts
packages/react-material-ui/src/index.ts

The scope of this PR is to implement persistence for the Table data on localStorage (for now, the idea is to have this integrated with BE in the future) every time the user changes the settings (toggle and/or change order of table columns). To structure the data saved, the `react-auth-provider` and `next/navigation` libs are used, for getting the logged user data and the current route, respectively.
The `ComposedTable` component was created so that the table settings can be present by default on every table instance. This component puts together the `Filter` and `Table` components, allowing the contents and settings handlers to be passed by props. Example of how to instance the `ComposedTable` as follows:
```jsx
<ComposedTable
rows={rows}
headers={headers} …
```

Save Table settings on local storage

---

packages/react-material-ui/src/components/Filter/Filter.tsx
packages/react-material-ui/src/components/OrderableDropDown/OrderableDropDown.tsx

This PR adds:
- `complementaryActions` and `additionalGridItems` can now receive render functions and have access to the filters state.
- minimum items alllowed in the filters

feat: allow filter to have min items and allow passing render function

---

packages/react-auth-provider/src/index.tsx
packages/react-auth-provider/src/interfaces/index.ts
packages/react-data-provider/src/ClientProvider.tsx
packages/react-data-provider/src/useDataProvider.ts

**Auth Provider**
- Change LoginParams interface to accept any keys with string or number
- Change authLogin function to accept the new LoginParams format
**Data Provider**
- Change useDataProvider and ClientProvider to accept onRefreshTokenError as optional
doLogin still works with username and password, which are suggested by the interface
doLogin now works with any other keys as long as they use string or number
ClientProvider's `onRefreshTokenError` prop is no longer mandatory

feat: auth and data providers enhancements

---

packages/react-material-ui/src/components/AutocompleteField/AutocompleteField.tsx
packages/react-material-ui/src/components/Table/Table.tsx
packages/react-material-ui/src/components/Table/TableBody/TableBodyCells.tsx
packages/react-material-ui/src/components/Table/TableHeader/TableHeaderCells.tsx
packages/react-material-ui/src/components/Table/types.ts
packages/react-material-ui/src/components/submodules/Table/MobileRowModal.tsx
packages/react-material-ui/src/components/submodules/Table/README.md
packages/react-material-ui/src/components/submodules/Table/index.tsx
packages/react-material-ui/src/modules/crud/index.tsx
packages/react-material-ui/src/utils/isMobile.ts

Add info modal for tables in mobile devices
How to use it?
Add "hideOnMobile: true" to the headers you want to hide in the regular table for mobile
You can pass the title source for the modal title.
```
<CrudModule
tableProps={{
mobileModalTitleSrc: 'fullName',
tableSchema: [
{
id: 'id',
label: 'ID',
hideOnMobile: true,
}
]
...
}}
/>
```

feat: add modal info for mobile table

---

packages/react-material-ui/src/components/FormLabel/index.tsx
packages/react-material-ui/src/components/OtpInput/index.tsx
packages/react-material-ui/src/styles/CustomWidgets/CustomOtpInputWidget.tsx
packages/react-material-ui/src/styles/CustomWidgets/index.ts

This PR adds compability to use OtpInput inside a React JsonSchema Form.
```typescript
<SchemaForm.Form
[...]
uiSchema={{
otp: {
'ui:widget': CustomOtpInputWidget,
},
}}
customValidate={(formData, error) =>
validateForm(formData, error, validationRules)
}
[...]
>
<Text
fontSize={theme.typography.caption.fontSize}
fontWeight={theme.typography.fontWeightMedium}
gutterBottom
sx={{ mt: 3 }}
>
Two factor authentication
</Text>
</SchemaForm.Form>
```
```typescript
export const validationRules: ValidationRule<SignInFormData>[] = [
{
field: 'otp',
test: value => !value,
message: 'OTP is required.',
},
{
field: 'otp',
test: value => value?.length < 4,
message: 'OTP is required.',
},
];
```

feat: add rjsf compability to otp input

---

packages/react-material-ui/src/components/OrderableDropDown/OrderableDropDown.tsx

This PR replaces the PointerSensor with MouseSensor and TouchSensor as recommended by the library maintainers to fix the issue with scrollable lists on mobile.
https://docs.dndkit.com/api-documentation/sensors/pointer

fix: replace pointer sensor with mouse and touch sensor to fix scrollable list issues

---

packages/react-material-ui/__tests__/Breadcrumbs.spec.tsx
packages/react-material-ui/src/components/Breadcrumbs/Breadcrumbs.tsx
packages/react-material-ui/src/components/Breadcrumbs/index.ts
packages/react-material-ui/src/components/Breadcrumbs/utils.ts
packages/react-material-ui/src/index.ts
packages/react-material-ui/src/modules/crud/index.tsx

Implementation of Breadcumbs component for route history using MUI's component. The routes should be passed as props, structured as an array of objects, each one containing `href` and `label`.

Implement Breadcrumbs component

---

packages/react-material-ui/src/components/ComposedTable/index.tsx
packages/react-material-ui/src/components/Filter/Filter.tsx
packages/react-material-ui/src/components/submodules/Filter/index.tsx
packages/react-material-ui/src/components/submodules/Table/index.tsx
packages/react-material-ui/src/hooks/useSettingsStorage.ts
packages/react-material-ui/src/modules/crud/index.tsx

This PR integrates the visibility and order settings from the Filter and ComposedTable components with the database through endpoints available at the Cache Module.

Integrate Filter settings with Cache Module endpoints

---

packages/react-material-ui/__tests__/CrudModule.spec.tsx
packages/react-material-ui/__tests__/SchemaForm.spec.tsx
packages/react-material-ui/src/components/Breadcrumbs/Breadcrumbs.tsx
packages/react-material-ui/src/components/ComposedTable/index.tsx
packages/react-material-ui/src/components/Filter/Filter.tsx
packages/react-material-ui/src/components/OrderableDropDown/OrderableDropDown.tsx
packages/react-material-ui/src/components/SchemaForm/SchemaForm.tsx
packages/react-material-ui/src/components/SearchField/SearchField.tsx
packages/react-material-ui/src/components/submodules/ModalForm/index.tsx
packages/react-material-ui/src/components/submodules/Table/MobileRowModal.tsx
packages/react-material-ui/src/components/submodules/Table/index.tsx

Theis PR adjusts the `buttonTitle` and `buttonComponent` props from SchemaForm component, in a way that it is passed correctly to the RJSF form, `buttonTitle` being part of the `uiSchema` and `buttonComponent` being a custom template.
The changes also include adjustments on the `Avatar` component import and renaming icon props so the compile time in child projects get optimized.

Adjust custom button props on SchemaForm

---

packages/react-material-ui/src/components/submodules/AuthForm/index.tsx
packages/react-material-ui/src/modules/auth/index.tsx

Change structure of AuthModule form header and title to accept custom nodes.
Custom header + custom title
Custom header + no title
Custom title + no header
No header + no title

Change structure of auth form header and title

---

packages/react-material-ui/src/components/TextField/TextField.tsx

This PR fixes issue #69, where multiple instances of `FormControl` were being rendered when the `TextField` component was used.
For this fix, the `MuiTextField` internal component was removed and the props separated into `FormControl`, `FormLabel` and `MuiOutlinedInput`, since `MuiTextField` implements a `FormControl` internally and thus accepts the same props.

Refactor structure of TextField component

---

packages/react-material-ui/__tests__/Dialog.spec.tsx
packages/react-material-ui/src/components/Dialog/Dialog.tsx

Change Dialog title prop to also accept other elements rather than only a string.
For the screenshot below, the Dialog composition was the following:
```tsx
<Dialog
open
handleClose={() => null}
title={
<div>
<p>Title</p>
<p>Subtitle</p>
</div>
}
footer={<div>Footer</div>}
>
<div>Body</div>
</Dialog>
```

Change Dialog title to accept ReactNode

---

packages/react-material-ui/src/components/submodules/AuthForm/index.tsx
packages/react-material-ui/src/components/submodules/Table/index.tsx
packages/react-navigation/src/components/DefaultRoute.tsx
packages/react-navigation/src/components/Resource.tsx
packages/react-navigation/src/components/RoutesRoot.tsx

Add `page` prop to DefaultRoute, in a way that a custom node can be rendered instead of a module on Resource instances.

Add page prop to DefaultRoute

---

packages/react-material-ui/src/components/submodules/AuthForm/index.tsx
packages/react-material-ui/src/modules/auth/README.md
packages/react-material-ui/src/modules/auth/constants.ts
packages/react-material-ui/src/modules/auth/index.tsx

Restructure AuthModule props so that they're passed in a clearer way by removing the `moduleProps` prop object and adding the `query` one, where props specific to the auth request are passed. The object previously passed via `moduleProps` now can be passed directly to the component.

Restructure Auth Module props

---

packages/react-material-ui/src/components/Drawer/Drawer.tsx
packages/react-navigation/src/components/AppBarContainer.tsx
packages/react-navigation/src/components/DefaultRoute.tsx
packages/react-navigation/src/components/Router.tsx
packages/react-navigation/src/components/RoutesRoot.tsx

Router now accepts `navbarProps` and `drawerProps` as props to forward to the Drawer and Nav props.
```
<Router
AdminProvider={AdminProvider}
navbarProps={{
avatar: "https://picsum.photos/200/200",
text: "Concepta",
subText: "Admin",
}}
drawerProps={{
items: [{ text: "test" }],
activeIconColor: "#FF0000",
iconColor: "#00FF00",
backgroundColor: "#000",
}}
>
```

feat: add drawerProps and navProps to Router

---

packages/react-material-ui/src/styles/CustomWidgets/CustomCheckboxWidget.tsx
packages/react-navigation/src/components/DefaultRoute.tsx
packages/react-navigation/src/components/Resource.tsx
packages/react-navigation/src/components/Router.tsx
packages/react-navigation/src/components/RoutesRoot.tsx

This PR renames defaultRoute to initialRoute and do not pass it down to authentication components.
It also adds showAppBar, useNavigateFilter, showDrawerItem and expand custom checkbox widget to render string or react node.

feat: rename defaultRoute to initialRoute and fix prop drilling

---

packages/react-material-ui/src/components/submodules/DrawerForm/index.tsx
packages/react-material-ui/src/components/submodules/Filter/index.tsx
packages/react-material-ui/src/components/submodules/ModalForm/index.tsx
packages/react-material-ui/src/components/submodules/Table/index.tsx
packages/react-material-ui/src/components/submodules/TableRowControls/index.tsx
packages/react-material-ui/src/components/submodules/types/Form.ts
packages/react-material-ui/src/modules/crud/index.tsx

Changes on this PR:
- Adjustment on flickering buttons inside the CrudModule form
- Adjustment on Filter grid placement based on screen width
- Improvement on Form submodule prop path
Desktop
Tablet
Mobile

Adjust flickering CrudModule form buttons and Filter row

---

packages/react-material-ui/src/modules/crud/index.tsx
packages/react-navigation/src/components/DefaultRoute.tsx

- Accept string or object with ReactNode as Title
- Accept an object with name and component as parameters
- Render title accordingly
- Use name to insert into breadcrumb
- Use name to pass to FormComponent
- Allow user to hide the breadcrumb
```
title: {
name: "Molecules",
component: (
<ScreenTitle
title="Molecules"
subtitle="List of available molecules on the system"
/>
),
},
hideBreadcrumb: true,
```

CrudModule - breadcrumb hide option / title component option

---

packages/react-material-ui/src/components/submodules/DrawerForm/index.tsx
packages/react-material-ui/src/components/submodules/ModalForm/index.tsx
packages/react-material-ui/src/components/submodules/types/Form.ts

The Cancel button should appear also in the Edit form. To achieve this goal, the Cancel button is now visible by default and the Delete button is visible only if the `isDeleteButtonVisible` form has a truthful value.

Add Cancel button to Crud edit form

---

packages/react-material-ui/src/modules/crud/index.tsx

Closes #245 
```
<CrudModule
...
tableProps={{
order: Order.Asc,
orderBy: "rankingPosition",
...
}}
/>
```

feat: crud module - allow initial sort

---

packages/react-material-ui/src/components/Drawer/Drawer.tsx

Adding children to the Drawer component so that additional content can be rendered below the menu items.

Add children to drawer component

---

packages/react-navigation/src/components/Router.tsx

Adjustments to initial route so the user is not redirect on page refresh.
How to use the new format:
```jsx
import { Router, Resource, ChildRoutes } from "@concepta/react-navigation";
<Router
rootElement={<AdminProvider />}
childRoutes={<Routes />}
initialRoute="/molecule"
/>
```

feat: adjust initial route to prevent redirect on refresh

---

packages/react-material-ui/src/hooks/useSettingsStorage.ts

Adjust user id on storage settings hook. The reason for the change is that in some cases the user id was not set in the first render, resulting on the cache list not being set on the filters.

Adjust user id on storage settings hook

---

packages/react-navigation/src/components/AppBarContainer.tsx
packages/react-navigation/src/components/ChildRoutes.tsx

The issue describes that the `AppBar` drawer `collapsed` state is being reset on every page change and the drawer should be rendered oustide of the route hierarchy. However, the `AppBar` visibility can be managed from inside the child routes, making it difficult to implement rendering outside of those routes.
This PR presents a solution by managing state from inside the `ChildRoutes`, so that every route change gets the correct state from the previous one.

Add handler for drawer state on ChildRoutes component

---

packages/react-data-provider/src/axiosClient.ts
packages/react-data-provider/src/interfaces/index.ts

This PR allows data provider to pass `responseType` to axios client. This way we can make requests for different responses (e.g. when we're trying to download a file that responds with a blob)

feat: allow data provider to pass responseType to axios client

---

packages/react-material-ui/src/components/DatePickerField/index.tsx
packages/react-material-ui/src/components/submodules/Filter/index.tsx

This PR fixes the debounced search function when the user is typing in the date picker field and also adjusts the filter onChange submodule to reflect the controlled state.

fix: debounced search function and filter onchange submodule

---

copy-css.js
package.json
packages/react-data-viz/README.md
packages/react-data-viz/package.json
packages/react-data-viz/src/index.ts
packages/react-data-viz/src/maps/Map.tsx
packages/react-data-viz/src/maps/MapMarkerCluster.tsx
packages/react-data-viz/src/maps/MarkerClusterGroup/index.tsx
packages/react-data-viz/src/maps/MarkerClusterGroup/styles.css
packages/react-data-viz/src/maps/index.ts
packages/react-data-viz/tsconfig.json
tsconfig.json
yarn.lock

This PR introduces the first draft of the `react-data-viz` package for Rockets, which provides easy-to-use, out-of-the-box data visualization components. The package includes both "raw" implementations of components and integrations with third-party tools (e.g., [Cube.dev](https://cube.dev/)). Below is an excerpt from the README for a quick overview. For a detailed explanation, please refer to the full README.
> The primary goal of this package is to provide easy-to-use, out-of-the-box data visualization components. Aligned with the mission of Rockets to offer a comprehensive end-to-end application, this package contributes by providing maps and charts for data visualization management.
> 
> We offer maps and charts that can be used with any dataset, as well as pre-integrated components …

feat: add react data viz package and first map component
