packages/react-material-ui/src/components/Table/Styles.ts
packages/react-material-ui/src/components/Table/Table.tsx
packages/react-material-ui/src/components/Table/TableStyles/MSWTableStyles.ts

Add props to allow Table customization
Add MSW visual styles to Table

feat: edit Table - add props to style and add MSW styles

---

packages/react-data-provider/src/axiosClient.ts
packages/react-data-provider/src/interfaces/index.ts

add signal (abort controller) param to request params

add signal (abort controller) param to request params

---

package.json
packages/react-material-ui/package.json
packages/react-material-ui/src/components/Table/Table.tsx
packages/react-material-ui/src/components/Table/useTable.ts
packages/react-material-ui/src/styles/CustomWidgets/CustomSelectWidget.tsx
yarn.lock

Add useTable hook and changes in Table component to support it

feat: add useTable hook

---

packages/react-material-ui/src/components/SchemaForm/SchemaForm.tsx
packages/react-material-ui/src/components/SchemaForm/Title.tsx
packages/react-material-ui/src/components/SchemaForm/utils/mapWidgetType.ts
packages/react-material-ui/src/components/SchemaForm/utils/uiSchemaGenerator.ts

This PR fixes SchemaForm imports

[FIX] SchemaForm imports

---

packages/react-material-ui/src/components/ContainerWithDrawer/ContainerWithDrawer.tsx
packages/react-material-ui/src/components/Drawer/Drawer.tsx
packages/react-material-ui/src/components/SchemaForm/SchemaForm.tsx
packages/react-material-ui/src/components/SchemaForm/Title.tsx
packages/react-material-ui/src/components/SchemaForm/utils/mapWidgetType.ts
packages/react-material-ui/src/components/Table/Table.tsx
packages/react-material-ui/src/styles/CustomTemplates/ObjectFieldTemplate.tsx
packages/react-material-ui/src/styles/CustomTemplates/index.ts
packages/react-material-ui/src/styles/CustomWidgets/CustomCheckboxesWidget.tsx

This PR makes small adjustments to components so they can be more flexible. Without this customization we're not able to tweak small layout things that might be necessary for different projects.
Some components would require bigger refactors, but for the sake of simplicity let's just add properties to extend the components.

feat: minor components adjustments to make it more flexible

---

packages/react-data-provider/src/axiosClient.ts
packages/react-data-provider/src/interfaces/index.ts
packages/react-data-provider/src/useDataProvider.ts

feat: add patch, put and delete requests

---

packages/react-material-ui/src/components/Table/hooks/useTableQueryState.ts
packages/react-material-ui/src/components/Table/types.ts
packages/react-material-ui/src/components/Table/useTable.ts
packages/react-material-ui/src/components/TextField/TextField.tsx
packages/react-material-ui/src/styles/CustomWidgets/CustomTextFieldWidget.tsx

This PR makes adjustments to simpleFilter in Table, add ui:formatter to TextField widget and add built-in validations from rSJF.

feat: more adjustments to table and form fields

---

packages/react-material-ui/src/components/Drawer/Drawer.tsx
packages/react-material-ui/src/components/Table/TableBody/TableBodyRows.tsx
packages/react-material-ui/src/components/Table/TablePaginationNumbers.tsx

Table pagination, table sorting and slicing and Drawer props
Ticket: [1112](https://sprints.zoho.com/team/conceptatech#itemdetails/P112/I1112)

feat: adjustments in Table and Drawer

---

packages/react-material-ui/src/components/AutocompleteField/AutocompleteField.tsx
packages/react-material-ui/src/components/AutocompleteField/index.ts
packages/react-material-ui/src/components/Filter/Filter.tsx
packages/react-material-ui/src/components/Filter/index.ts
packages/react-material-ui/src/components/SearchField/SearchField.tsx
packages/react-material-ui/src/components/SearchField/index.ts
packages/react-material-ui/src/components/SelectField/SelectField.tsx
packages/react-material-ui/src/components/SelectField/index.ts
packages/react-material-ui/src/index.ts

This PR adds a Filter component that receives a `filters` prop to render fields that are supposed to filter given data. 
The filter object provided to filters prop accepts three types of fields:
```
1. FilterType.Text,
2. FilterType.Autocomplete,
3. FilterType.Select
```
Each of these types have different required props. Please check the types to know which props are required for each type of field.
This PR also adds:
- AutocompleteField
- SelectField
It's not in the scope of this PR to integrate this with table/data provider because we still need to work on useTable hook to be able to use it inside of other components. Currently every time useTable gets invoked it gets new data created because it's not tied to any React Context.
```
<Filter
filters={[
{
type: FilterType.Text, …
```

feat: add filter component

---

packages/react-material-ui/src/components/Table/README.md

Create documentation for the Table component, including the main topics necessary for the usage of data, states and hooks implementation.

Create table component readme

---

packages/react-material-ui/src/styles/CustomWidgets/CustomAutocompleteWidget.tsx

This PR adds autocomplete renderOptions and select all feature.

feat: add autocomplete render options and select all

---

packages/react-material-ui/src/styles/CustomWidgets/CustomAutocompleteWidget.tsx

This PR adds ability to:
- pass `additionalProps` to render additional props to the array of options when data is fetched by the component
- Avoid repeated items in multiselect autocomplete

feat: add additionalProps and remove repeated items from autocomplete widget

---

packages/react-material-ui/src/components/AutocompleteField/AutocompleteField.tsx
packages/react-material-ui/src/components/SelectField/SelectField.tsx

This PR makes layout adjustments to `SelectField` and `AutocompleteField`

feat: adjust select and autocomplete fields

---

packages/react-material-ui/src/components/SelectField/SelectField.tsx

This PR makes the 'all optional' removable from select field.

feat: make all option removable from select field

---

packages/react-material-ui/package.json
packages/react-material-ui/src/components/Table/TableBody/TableBodyCells.tsx
packages/react-material-ui/src/components/Table/TableHeader/TableHeaderCells.tsx
packages/react-material-ui/src/components/Table/TableHeaderCustomization.tsx
packages/react-material-ui/src/components/Table/TableRoot.tsx
packages/react-material-ui/src/components/Table/hooks/useTableRoot.tsx
packages/react-material-ui/src/components/Table/index.ts
packages/react-material-ui/src/components/Table/types.ts
yarn.lock

ATTENTION: THIS IS A WORK IN PROGRESS PULL REQUEST, EXPECTED CHANGES IN THE NEAR FUTURE!

feat: start implementing column management in table component

---

packages/react-material-ui/src/components/FormTemplate/FormTemplate.tsx

This PR fixes the form template component unit tests

fix: form template unit tests

---

packages/react-material-ui/src/components/Filter/Filter.tsx
packages/react-material-ui/src/components/submodules/Filter/index.tsx
packages/react-material-ui/src/components/submodules/Table/index.tsx
packages/react-material-ui/src/modules/crud/index.tsx

This PR contains small fixes for the crud modules feature

fix: general crud modules adjustments

---

packages/react-material-ui/__tests__/CrudModule.spec.tsx

[Tests - Crud Module](https://sprints.zoho.com/workspace/conceptatech#P112/itemdetails/I1303)
Adds tests for Crud Module

feat: tests for crud module

---

packages/react-material-ui/__tests__/descendingComparator.spec.ts
packages/react-material-ui/__tests__/getComparator.spec.ts
packages/react-material-ui/__tests__/mapAdvancedProperties.spec.ts
packages/react-material-ui/__tests__/mapEnumToCheckbox.spec.ts
packages/react-material-ui/__tests__/mapEnumToSchema.spec.ts
packages/react-material-ui/__tests__/sortTable.spec.ts
packages/react-material-ui/__tests__/stableSort.spec.ts
packages/react-material-ui/__tests__/useTable-mockData.spec.tsx
packages/react-material-ui/__tests__/useTable.spec.tsx
packages/react-material-ui/__tests__/validation.spec.ts
packages/react-material-ui/src/components/SchemaForm/utils/mapAdvancedProperties.ts

[Missing/incomplete code coverage](https://sprints.zoho.com/workspace/conceptatech#P112/itemdetails/I1306), [useTable.ts tests](https://sprints.zoho.com/workspace/conceptatech#P112/itemdetails/I1315)
Adds tests for several functions and hooks

feat: add tests for several hooks and functions

---

packages/react-material-ui/src/components/OrderableDropDown/OrderableDropDown.tsx

This PR fixes the pointer sensor from dnd-kit in the orderabledropdown.
Tested with touch/pen and mouse.

fix: pointer sensor dnd-kit

---

packages/react-material-ui/src/modules/users/constants.ts
packages/react-material-ui/src/modules/users/index.tsx

This PR adds create form to UsersModule by default

feat: add create form to users module

---

packages/react-material-ui/src/components/AutocompleteField/AutocompleteField.tsx
packages/react-material-ui/src/components/Filter/Filter.tsx
packages/react-material-ui/src/components/submodules/Filter/index.tsx

This PR adds the feature to request a resource from within the AutocompleteField component.
It is also implemented in Filter and CrudModule
`resource`: the name of the resource in the api
`resourceValue - optional (default: id)`: the name of the property to get the value from
`resourceLabel - optional (default: name)`: the name of the property to get the label from

feat: add autocomplete resource request

---

packages/react-material-ui/__tests__/Filter.spec.tsx
packages/react-material-ui/src/components/AutocompleteField/AutocompleteField.tsx
packages/react-material-ui/src/components/Filter/Filter.tsx
packages/react-material-ui/src/components/SelectField/SelectField.tsx
packages/react-material-ui/src/components/Table/TableCellSkeleton.tsx
packages/react-material-ui/src/components/submodules/Filter/index.tsx
packages/react-material-ui/src/modules/crud/useCrudRoot.tsx

This PR adds the multiple select filter and performs small fixes to use components apart from CrudModules.

feat: add multiple select filter and small fixes

---

packages/react-material-ui/src/components/Filter/Filter.tsx

This PR fixes the hide prop of the filter order.

fix: hide filter if condition mets

---

packages/react-material-ui/src/modules/auth/README.md
packages/react-material-ui/src/modules/crud/README.md

Improve documentation for Crud and Auth modules, providing more details on the implementation process.

Improve documentation for Crud and Auth modules

---

packages/react-material-ui/__tests__/OrderableDropDown.spec.tsx
packages/react-material-ui/src/components/Filter/Filter.tsx
packages/react-material-ui/src/components/OrderableDropDown/OrderableDropDown.tsx
packages/react-material-ui/src/components/Table/TableColumnOrderable.tsx
packages/react-material-ui/src/components/TextField/PasswordStrengthRules.tsx
packages/react-material-ui/src/components/submodules/Filter/index.tsx
packages/react-material-ui/src/components/submodules/Table/index.tsx
packages/react-material-ui/src/modules/crud/index.tsx

Solves #116
https://github.com/conceptadev/rockets-react/assets/14095527/4f0a812e-ee48-46de-9a65-b2782333c700

feat: add select/deselect all to orderable dropdown

---

packages/react-material-ui/src/components/Table/TableBody/TableBodyCells.tsx

This PR handles the case where the value might be null in the render cell function. I'm also refactoring a little bit to make the code more concise.
Solves #121

feat: fix null values on render cell function

---

packages/react-material-ui/src/components/TextField/utils.ts

fix textfield type error on next 14

feat: fix textfield type error on next 14

---

packages/react-material-ui/src/components/Table/TableBody/TableBodyCheckbox.tsx
packages/react-material-ui/src/components/Table/TableHeader/TableHeaderCheckbox.tsx

Add TableCellProps to table's header and body checkbox cells

feat: fix checkbox cell props

---

packages/react-material-ui/src/components/Drawer/Drawer.tsx
packages/react-material-ui/src/components/Drawer/DrawerItem.tsx
packages/react-material-ui/src/components/Drawer/index.ts

This PR adjusts the drawer styles to be more generic and allow the project that's using it to compose its styles.

fix: drawer styles to be more generic

---

packages/react-material-ui/src/components/AppBar/README.md
packages/react-material-ui/src/components/ComposedTable/README.md
packages/react-material-ui/src/components/Filter/README.md
packages/react-material-ui/src/components/SchemaForm/README.md
packages/react-material-ui/src/components/Table/README.md
packages/react-material-ui/src/utils/form/README.md

Documentation for the following components and functions:
- AppBar
- Filter
- Table
- ComposedTable
- SchemaForm
- validateForm

Component documentations

---

packages/react-auth-provider/README.md
packages/react-auth-provider/src/index.tsx
packages/react-auth-provider/src/interfaces/index.ts
packages/react-data-provider/README.md
packages/react-data-provider/src/ClientProvider.tsx
packages/react-data-provider/src/useDataProvider.ts

auth / data provider docs

---

packages/react-material-ui/__tests__/Drawer.spec.tsx
packages/react-material-ui/__tests__/DrawerItem.spec.tsx
packages/react-material-ui/src/components/AppBar/AppBarDrawer.tsx
packages/react-material-ui/src/components/Drawer/Drawer.tsx
packages/react-material-ui/src/components/Drawer/DrawerItem.tsx
packages/react-material-ui/src/components/Drawer/index.ts
packages/react-material-ui/src/index.ts
stories/AppBar.stories.tsx
stories/Drawer.stories.tsx

- Add Storybook stories for the Drawer component
- Add TSDocs notations in Drawer component

feat: storybook - add Drawer stories / add tsdocs for drawer component

---

.storybook/preview.tsx
packages/react-material-ui/__tests__/Navbar.spec.tsx
packages/react-material-ui/src/components/AppBar/AppBarNav.tsx
packages/react-material-ui/src/components/HeaderAccount/HeaderAccount.tsx
packages/react-material-ui/src/components/Navbar/Navbar.tsx
packages/react-material-ui/src/components/Navbar/index.ts
packages/react-material-ui/src/index.ts
stories/Navbar.stories.tsx

Ticket: [Navbar Docs](https://sprints.zoho.com/workspace/conceptatech#P112/itemdetails/I1645)

Storybook - Navbar stories / TSDocs for Navbar component

---

packages/react-material-ui/__tests__/Avatar.spec.tsx
packages/react-material-ui/__tests__/CrudModule.spec.tsx

Adjustments on import on Avatar test file and title prop on Crud Module.

Adjust test for Avatar and Crud Module

---

packages/react-material-ui/src/components/Text/Text.tsx
stories/Text.stories.tsx

feat: add Text storybook and tsDocs

---

packages/react-material-ui/src/components/SearchField/SearchField.tsx
stories/SearchField.stories.tsx

feat: add SearchField storybook and tsDocs

---

packages/react-material-ui/src/components/SchemaForm/SchemaForm.tsx
packages/react-material-ui/src/components/SchemaForm/types.ts
stories/SchemaForm.stories.tsx

feat: add SchemaForm storybook and tsDocs

---

packages/react-material-ui/__tests__/TextField.spec.tsx
packages/react-material-ui/src/components/OtpInput/index.tsx
packages/react-material-ui/src/components/TextField/TextField.tsx
packages/react-material-ui/src/components/TextField/index.ts
packages/react-material-ui/src/index.ts
packages/react-material-ui/src/styles/CustomWidgets/CustomAutocompleteWidget.tsx
packages/react-material-ui/src/styles/CustomWidgets/CustomTextFieldWidget.tsx
stories/TextField.stories.tsx

feat: storybook - textfield

---

packages/react-material-ui/src/components/Dialog/Dialog.tsx
packages/react-material-ui/src/components/Dialog/index.ts
packages/react-material-ui/src/index.ts
stories/Dialog.stories.tsx
stories/SideModal.stories.tsx

feat: storybook - Dialog

---

packages/react-material-ui/__tests__/Image.spec.tsx
packages/react-material-ui/src/components/Drawer/Drawer.tsx
packages/react-material-ui/src/components/Image/Image.tsx
packages/react-material-ui/src/components/Image/index.ts
packages/react-material-ui/src/components/submodules/AuthForm/index.tsx
packages/react-material-ui/src/index.ts
stories/Image.stories.tsx

feat: storybook - image

---

packages/react-material-ui/__tests__/Dialog.spec.tsx
packages/react-material-ui/__tests__/FormFieldSkeleton.spec.tsx
packages/react-material-ui/__tests__/SideModal.spec.tsx

feat: fix tests imports

---

packages/react-material-ui/__tests__/Dropdown.spec.tsx
packages/react-material-ui/src/components/Dropdown/Dropdown.tsx
packages/react-material-ui/src/components/Dropdown/index.ts
packages/react-material-ui/src/index.ts
stories/Dropdown.stories.tsx

feat: storybook - dropdown

---

packages/react-material-ui/__tests__/FormFieldSkeleton.spec.tsx
packages/react-material-ui/src/components/AutocompleteField/AutocompleteField.tsx
packages/react-material-ui/src/components/FormFieldSkeleton/index.tsx
packages/react-material-ui/src/components/SelectField/SelectField.tsx
packages/react-material-ui/src/index.ts
packages/react-material-ui/src/styles/CustomWidgets/CustomAutocompleteWidget.tsx
stories/FormFieldSkeleton.stories.tsx

feat: storybook - formFieldSkeleton

---

package.json
packages/react-auth-provider/src/index.tsx
packages/react-auth-provider/src/interfaces/index.ts
packages/react-material-ui/src/components/AppBar/AppBarDrawer.tsx
packages/react-material-ui/src/components/AppBar/AppBarNav.tsx
packages/react-material-ui/src/components/AppBar/hooks/index.ts
packages/react-material-ui/src/components/AppBar/hooks/useAppBarRoot.tsx
packages/react-material-ui/src/components/Table/hooks/index.ts
packages/react-material-ui/src/components/Table/hooks/useTableRoot.tsx
packages/react-material-ui/src/components/Table/index.ts
packages/react-material-ui/src/components/Table/useTable.ts
packages/react-material-ui/src/hooks/index.ts
packages/react-material-ui/src/index.ts
packages/react-material-ui/src/modules/crud/index.tsx
packages/react-material-ui/src/modules/crud/useCrudRoot.tsx
public/mockServiceWorker.js
typedoc.json
yarn.lock

Docs for the following hooks:
- useAuth
- useAppBarRoot
- useCrudRoot
- useTableRoot
- useTable

Documentation for hooks/context

---

packages/react-material-ui/__tests__/Switch.spec.tsx
packages/react-material-ui/src/components/Switch/Switch.tsx
packages/react-material-ui/src/components/Switch/index.ts
packages/react-material-ui/src/index.ts
packages/react-material-ui/src/styles/CustomWidgets/CustomSwitchWidget.tsx
stories/Switch.stories.tsx

feat: storybook / tsdocs - Switch

---

packages/react-material-ui/__tests__/FormLabel.spec.tsx
packages/react-material-ui/src/components/FormLabel/index.tsx
packages/react-material-ui/src/components/OtpInput/index.tsx
packages/react-material-ui/src/components/RadioGroup/RadioGroup.tsx
packages/react-material-ui/src/components/Select/Select.tsx
packages/react-material-ui/src/components/TextField/TextField.tsx
packages/react-material-ui/src/index.ts
stories/FormLabel.stories.tsx

feat: storybook / tsdocs - FormLabel

---

packages/react-material-ui/__tests__/Checkbox.spec.tsx
packages/react-material-ui/src/components/Checkbox/Checkbox.tsx
packages/react-material-ui/src/components/Checkbox/index.ts
packages/react-material-ui/src/index.ts
packages/react-material-ui/src/styles/CustomWidgets/CustomCheckboxWidget.tsx
packages/react-material-ui/src/styles/CustomWidgets/CustomCheckboxesWidget.tsx
stories/Checkbox.stories.tsx
stories/Switch.stories.tsx

feat: storybook / tsdocs - Checkbox

---

packages/react-material-ui/__tests__/FormTemplate.spec.tsx
packages/react-material-ui/src/components/FormTemplate/FormTemplate.tsx
packages/react-material-ui/src/components/FormTemplate/index.ts
packages/react-material-ui/src/index.ts
public/mockServiceWorker.js
stories/FormTemplate.stories.tsx
yarn.lock

feat: storybook / tsdocs - FormTemplate

---

packages/react-material-ui/__tests__/Link.spec.tsx
packages/react-material-ui/src/components/Link/Link.tsx
packages/react-material-ui/src/components/Link/index.ts
packages/react-material-ui/src/components/submodules/AuthForm/index.tsx
packages/react-material-ui/src/index.ts
stories/Link.stories.tsx

feat: storybook / TSDocs - Link

---

packages/react-material-ui/__tests__/SelectField.spec.tsx
packages/react-material-ui/src/components/Filter/Filter.tsx
packages/react-material-ui/src/components/SelectField/SelectField.tsx
packages/react-material-ui/src/components/SelectField/index.ts
packages/react-material-ui/src/index.ts
stories/SelectField.stories.tsx

feat: storybook / TSDocs - SelectField

---

packages/react-navigation/src/components/ForgotPasswordRoute.tsx
packages/react-navigation/src/components/ResetPasswordRoute.tsx
packages/react-navigation/src/components/SignUpRoute.tsx

Adjust auth route props to match AuthModule structure

Adjust auth route props

---

packages/react-material-ui/__tests__/Select.spec.tsx
packages/react-material-ui/src/components/Select/Select.tsx
packages/react-material-ui/src/components/Select/index.ts
packages/react-material-ui/src/index.ts
packages/react-material-ui/src/styles/CustomWidgets/CustomSelectWidget.tsx
stories/Select.stories.tsx

feat: storybook / TSDocs - Select

---

packages/react-material-ui/src/components/submodules/AuthForm/index.tsx
packages/react-material-ui/src/modules/auth/index.tsx

Changes on this PR:
- Adjust AuthModule structure to render components of different sizing;
- Expand props to accept AuthFormSubmodule and avoid repetition.

Expand AuthModule props and fix main container

---

packages/react-navigation/src/components/DefaultRoute.tsx
packages/react-navigation/src/components/Resource.tsx
packages/react-navigation/src/components/Router.tsx
packages/react-navigation/src/components/RoutesRoot.tsx

Add default route and unprotected routes to Rockets Navigation

feat: add default route and unprotected routes

---

packages/react-material-ui/src/components/Drawer/Drawer.tsx

fix button navigation after prop change

feat: drawer - fix button navigation after prop change

---

packages/react-material-ui/src/components/submodules/DrawerForm/index.tsx
packages/react-material-ui/src/components/submodules/ModalForm/index.tsx
packages/react-material-ui/src/components/submodules/types/Form.ts
packages/react-material-ui/src/modules/crud/index.tsx

- Add sx to form schemas
- Add id and className 
```jsx
editFormProps={{
formSchema: editSchema,
sx: {
"& .MuiDrawer-paperAnchorRight": {
width: "600px",
maxWidth: "600px",
},
},
}}
```

CrudModule - Id, class and sx

---

packages/react-material-ui/src/components/SchemaForm/SchemaForm.tsx
packages/react-material-ui/src/components/submodules/DrawerForm/index.tsx

Fix crud module drawer form validations

feat: crudModule - fix drawerForm submit validations

---

packages/react-data-provider/src/ClientProvider.tsx

Fix base url on refresh
closes #225

feat: data provider - fix baseUrl on refresh

---

packages/react-material-ui/src/components/submodules/DrawerForm/index.tsx
packages/react-material-ui/src/components/submodules/ModalForm/index.tsx
packages/react-material-ui/src/modules/crud/index.tsx
packages/react-navigation/src/components/AuthRoute.tsx

Adjustment on CrudModule form fields that prevent them from being erased or reset when the submit request is settled.
Resolves #227

Adjust CrudModule form values when request is settled

---

packages/react-material-ui/src/modules/crud/index.tsx

Add `isDeleteButtonVisible` prop to CrudModule `formProps` interface.

Add delete button visibility prop to crud module

---

packages/react-material-ui/src/modules/crud/index.tsx

feat: useCrudControls - fix refreshTable

---

packages/react-material-ui/src/components/Filter/Filter.tsx
packages/react-material-ui/src/components/MultiSelect/MultiSelect.tsx

This PR fixes the MultiSelect all option and adjusts the filter grid system to reflect the correct width and columns

fix: multiselect all option and filter grid system

---

packages/react-material-ui/src/components/submodules/AuthForm/index.tsx
packages/react-navigation/src/components/AppBarContainer.tsx

This PR makes AppBar container expand to full container width and adds flexibility to override any prop.

feat: add app bar container full width flexibility

---

packages/react-material-ui/src/components/DatePickerField/index.tsx

This PR fixes the debounced search function dependencies.

fix: date picker field debounced search function dependency array
